# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-11 04:08
from __future__ import unicode_literals

import Projects.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Name', models.CharField(max_length=255)),
                ('Research_Area', models.CharField(blank=True, choices=[('Astronomy', 'Astronomy'), ('Bioinformatics', 'Bioinformatics'), ('Machine Learning', 'Machine Learning'), ('Chemistry and Material Science', 'Chemistry and Material Science'), ('Computer Science', 'Computer Science'), ('Computational Space Physics', 'Computational Space Physics'), ('Computational and Fluid Dynamics', 'Computational and Fluid Dynamics'), ('Others', 'Other')], default='', max_length=150)),
                ('Project_Description', models.TextField(max_length=4000)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('UpdatedDate', models.DateField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Completed', 'Completed')], default='Pending', max_length=150)),
                ('project_code', models.CharField(default=Projects.models.increment_project_number, editable=False, max_length=50)),
                ('Number_CPU', models.PositiveIntegerField(blank=True, default='0', verbose_name='Number of Cores ')),
                ('Memory_required', models.PositiveIntegerField(blank=True, default='0', verbose_name='Memory (GB)')),
                ('Storage', models.PositiveIntegerField(blank=True, default='0', verbose_name='Storage (GB)')),
                ('Approved_by', models.CharField(blank=True, choices=[['admin', 'admin']], default='Not Assigned yet', max_length=150)),
                ('OS_Type', models.CharField(blank=True, choices=[('Windows', 'Windows'), ('Ubuntu', 'Ubuntu'), ('Centos', 'Centos'), ('Red hat', 'Red hat'), ('Suse', 'Suse'), ('Debian', 'Debian')], default='', max_length=150, verbose_name='Image')),
                ('Review', models.TextField(default='This Project is not yet Reviewed...!', max_length=200, verbose_name='Recommendation')),
                ('Project_Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project List',
                'db_table': 'project',
                'ordering': ['-project_code'],
            },
        ),
    ]
