# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-23 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectinfo',
            name='Discipline',
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='Research_area',
            field=models.CharField(blank=True, choices=[('Astro', 'Astronomy'), ('Bio', 'Bioinformatics'), ('ML', 'Machine Learning'), ('CMS', 'Chemistry and Material Science'), ('CS', 'Computer Science'), ('CSP', 'Computational Space Physics'), ('CFD', 'Computational and Fluid Dynamics'), ('Others', 'Other')], default='', max_length=15),
        ),
    ]
