# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-23 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200323_2249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectinfo',
            old_name='created_at',
            new_name='Created_at',
        ),
        migrations.RenameField(
            model_name='projectinfo',
            old_name='Research_area',
            new_name='Research_Area',
        ),
    ]
