# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-24 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200323_2255'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projectinfo',
            table='project',
        ),
    ]
