# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-17 21:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=140)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('alt_email', models.EmailField(max_length=150, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('mobile', models.CharField(max_length=15, null=True)),
                ('gender', models.CharField(max_length=11, null=True)),
                ('nationality', django_countries.fields.CountryField(max_length=2, null=True)),
                ('institution', models.TextField(max_length=130, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
