# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-19 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200318_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='alt_email',
            field=models.EmailField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('unspecified', 'unspecified')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='institution',
            field=models.CharField(blank=True, choices=[('UCT', 'University of Cape Town'), ('UKZN', 'University of Kwazulu Natal'), ('UP', 'University of Pretoria'), ('UWC', 'University of the Western Cape'), ('SUN', 'Stellenbosch University'), ('Wits', 'University of Witwatersrand'), ('UL', 'University of Limpopo'), ('UJ', 'University of Johannesburg'), ('TUT', 'Tshwane University of Technology'), ('UNISA', 'University of South Africa'), ('CPUT', ' Cape Peninsula University of Technology'), ('UNIVEN', 'University of Venda'), ('DUT', 'Durban University of Technology'), ('VUT', 'Vaal University of Technology'), ('WSU', 'Walter Sisulu University'), ('NMMU', 'Nelson Mandela University'), ('SMU', 'Sefako Makgatho Health Sciences University'), ('UMP', 'Mpumalanga University'), ('SPO', 'Sol Plaatjie University'), ('UJ', 'University of Johannesburg'), ('UFS', 'University of the Free State'), ('RU', 'Rhodes University'), ('NWU', ' North-West University'), ('UFH', 'University of Fort Hare')], default='', max_length=14),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
