# Generated by Django 3.0.4 on 2020-04-01 03:00

import django.core.validators
from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200331_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=150, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
    ]
