# Generated by Django 3.0.4 on 2020-04-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200401_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('Pend', 'Pending'), ('Decl', 'Decline'), ('Appro', 'Approval')], default='', max_length=14),
        ),
    ]
