# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-05 14:56
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Current_Position', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.CharField(blank=True, default='', max_length=150)),
                ('city', models.CharField(blank=True, default='', max_length=150)),
                ('region', models.CharField(blank=True, default='', max_length=150, verbose_name='Province ')),
                ('postal_code', models.CharField(blank=True, default='', max_length=150)),
                ('Country', django_countries.fields.CountryField(blank=True, default='', max_length=2)),
                ('institution', models.CharField(blank=True, choices=[(' Cape Peninsula University of Technology', ' Cape Peninsula University of Technology'), (' North-West University', ' North-West University'), ('Centre For High Performance Computing', 'Centre For High Performance Computing'), ('Durban University of Technology', 'Durban University of Technology'), ('Mpumalanga University', 'Mpumalanga University'), ('Nelson Mandela University', 'Nelson Mandela University'), ('Rhodes University', 'Rhodes University'), ('SMU', 'Sefako Makgatho Health Sciences University'), ('Sol Plaatjie University', 'Sol Plaatjie University'), ('Stellenbosch University', 'Stellenbosch University'), ('Tshwane University of Technology', 'Tshwane University of Technology'), ('University of Cape Town', 'University of Cape Town'), ('University of Fort Hare', 'University of Fort Hare'), ('University of Johannesburg', 'University of Johannesburg'), ('University of Johannesburg', 'University of Johannesburg'), ('University of Kwazulu Natal', 'University of Kwazulu Natal'), ('University of Limpopo', 'University of Limpopo'), ('University of Pretoria', 'University of Pretoria'), ('University of South Africa', 'University of South Africa'), ('University of Venda', 'University of Venda'), ('University of Witwatersrand', 'University of Witwatersrand'), ('University of the Free State', 'University of the Free State'), ('University of the Western Cape', 'University of the Western Cape'), ('Vaal University of Technology', 'Vaal University of Technology'), ('Walter Sisulu University', 'Walter Sisulu University')], default='', max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
