# Generated by Django 3.0.3 on 2020-03-03 15:17

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Dr', 'Dr'), ('Prof', 'Prof'), ('Rev', 'Rev')], max_length=4)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('alt_email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('mobile', models.CharField(max_length=15)),
                ('genger', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('unspecified', 'unspecified')], max_length=11)),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('institution', models.TextField()),
            ],
        ),
    ]
