# Generated by Django 3.0.3 on 2020-03-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Finished', 'Finished'), ('Disabled', 'Disabled')], max_length=10)),
                ('shortname', models.CharField(max_length=10)),
                ('discipline', models.CharField(max_length=10)),
                ('project_user', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('date_created', models.DateField(auto_now=True)),
                ('date_approved', models.DateField()),
            ],
        ),
    ]
