# Generated by Django 3.0.3 on 2020-03-04 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_projects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
