# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-03-19 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20200318_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='last_updated',
            new_name='created_at',
        ),
    ]
